language: python
python:
  - "3.7"
cache: pip
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip install -r requirements.txt
  - pip3 install -U pytest
script:
  - python3 -m pytest
